= ClojureScript Unraveled (2nd edition)
Andrey Antukh <niwi@niwi.nz>; Alejandro Gómez <alejandro@dialelo.com>
v6, 2019-07-16
:toc: left
:toclevels: 3
:doctype: book
:numbered:
:source-highlighter: pygments
:pygments-style: friendly
:idseparator: -
:idprefix:
:sectlinks:
:imagesdir: ./images
//^:source-highlighter: coderay
//^:listing-caption: Listing


== About this book

本書は、プログラミング言語であるClojureScriptを取り上げ、その開発ツールの詳細なガイドとなるとともに、ClojureScriptでの日々のプログラミングに役立つトピックについての記事を紹介しています。

この本は、読者が少なくとも1つの言語でプログラミングをした経験があることを前提としている点で、プログラミングの入門書ではありません。しかし、_Clojure_や関数型プログラミングの経験を前提としているわけではありません。誰もが知っているわけではないClojureScriptの理論的裏付けについて話すときには、参考資料へのリンクを含めるようにします。

ClojureScriptのドキュメントは充実していますが、数が少ないため、私たちはClojureScriptの入門書として、また一連の実用的なハウツーとして役立つ参考情報や豊富な例をまとめたものを書きたいと考えました。このドキュメントは、ClojureScript言語とともに進化し、言語機能のリファレンスとして、また、実用的なプログラミングレシピを集めた料理本のようなものとして、進化していきます。

以下のような方は、この本を最大限に活用できるでしょう。

- ClojureScriptや関数型プログラミングに興味があり、ある程度のプログラミング経験がある。
- ClojureScriptに興味があり、プログラミングの経験がある。
- すでにClojureを知っていて、ClojureScriptとClojureの違いや、同じコードベースで両方の言語をターゲットにする方法などの実用的なトピックを学びたい方。

自分が上記のグループのどれにも当てはまらなくても、気を落とさないでください。この本を試してみて、どうすればもっとアクセスしやすくなるか、フィードバックしてくださることをお勧めします。 私たちの目標は、ClojureScriptを新規参入者にとってより親しみやすいものにし、Clojureが普及に貢献したプログラミングに関する考え方を広めることであり、そこに多くの価値を見出しているからです。

この本の翻訳の一覧です。

- Ukrainian: https://lambdabooks.github.io/clojurescript-unraveled/


== Introduction

[quote, Rich Hickey]
なぜこんなことをするのか？それは、Clojure が _rocks_ で、JavaScript が _reach_ だからです。

_ClojureScript_は、JavaScriptをターゲットにしたClojureプログラミング言語の実装です。このため、Webブラウザ、Node.js、Nashorn（その他多数）など、さまざまな実行環境で実行することができます。

JavaScriptにコンパイルすることを目的とした他の言語（TypeScript、FunScript、CoffeeScriptなど）とは異なり、ClojureScriptはバイトコードのようにJavaScriptを使用するように設計されています。 関数型プログラミングを採用しており、非常に安全で一貫性のあるデフォルトを持っています。そのセマンティクスはJavaScriptのそれとは大きく異なります。

他の言語とのもう一つの大きな違い(そして私たちの意見では利点)は、Clojure(Script)がゲストとして設計されていることです。Clojure(Script)は独自の仮想マシンを持たない言語であり、実行環境のニュアンスに簡単に対応することができます。これには、Clojure(そしてClojureScript)が、ホスト言語用に書かれたすべての既存ライブラリにアクセスできるという利点があります。

本題に入る前に、ClojureScriptがもたらす核となるアイデアをいくつかまとめてみましょう。今すぐにすべてを理解できなくても心配しないでください。

- ClojureScriptは、その設計上の決定やイディオムによって、関数型プログラミングのパラダイムを実施します。関数型プログラミングについては強い意見を持っていますが、理論的な純粋さを追求するのではなく、実際的な言語です。
- 不変データを使ったプログラミングを推奨しており、高パフォーマンスで最先端の不変コレクションの実装を提供しています。
- アイデンティティとその状態を明確に区別し、変化を一連の不変的な値として管理するための明示的な構造を備えています。
- 型ベースおよび値ベースのポリモーフィズムを持ち、式の問題をエレガントに解決します。
- Lispの方言であるため、プログラムはプログラミング言語自身のデータ構造で記述されます。これは、_homoiconicity_と呼ばれる特性で、メタプログラミング（プログラムを書くプログラム）を可能な限りシンプルにします。

これらの考え方は、ClojureScriptを使用していなくても、ソフトウェアの設計や実装の方法に大きな影響を与えます。関数型プログラミング、（不変である）データとそれを変換するための操作との切り離し、時間経過に伴う変化を管理するための明示的なイディオム、抽象的なものにプログラミングするためのポリモーフィックな構造は、私たちが書くシステムを大幅に単純化します。

[quote, Rich Hickey]
私たちは、今日作っているのとまったく同じソフトウェアを、劇的にシンプルなもので作ることができます。劇的にシンプルな言語、ツール、技術、アプローチで。

この本を楽しんでいただき、ClojureScriptが、私たちにもたらしたのと同じ喜びとインスピレーションをもたらしてくれることを願っています。


== Language (the basics)

この章では、Clojure言語の予備知識を前提としない、ClojureScriptのちょっとした紹介を行い、ClojureScriptについて知り、本書の残りの部分を理解するのに必要なすべての事柄を簡単に説明します。

コードスニペットは、オンライン・インタラクティブ・レプリケーションで実行することができます。
http://www.clojurescript.io/

include::language-basics.adoc[]


== Tooling & Compiler

本章では、ClojureScriptを使った開発を容易にするための既存のツールを少し紹介します。前の章とは異なり、この章ではそれぞれ独立した異なるストーリーを語ることを意図しています。

include::compiler.adoc[]


== Language (advanced topics)

この章では、言語の一部であり、第1章では収まりきらない高度なトピックを説明します。この章の候補としては、トランスデューサ、コアプロトコル、トランジェント、メタデータなどが挙げられます。要約すると、言語を理解するために必須ではないトピックです。

include::language-advanced.adoc[]


== Acknowledgments

include::acknowledgments.adoc[]


== Further Reading

ClojureScriptに関するその他のリソースのリストです。

* https://github.com/clojure/clojurescript/wiki[ClojureScript wiki]: ClojureScriptに関するコミュニティが運営するWikiです。
* https://github.com/cljsinfo/cljs-api-docs/blob/catalog/INDEX.md[API Reference]: コミュニティで管理される完全な言語APIリファレンスです。
* http://cljs.info/cheatsheet/[ClojureScript Cheatsheet]: ClojureScript言語の包括的なリファレンスです。
* http://catcode.com/etudes-for-clojurescript/toc.html[Études for ClojureScript]: ClojureScriptを学ぶための練習問題集です。
* http://clojurescriptmadeeasy.com/[ClojureScript made easy]: ClojureScriptでよくある問題を解決するための短い記事を集めたものです。
* http://google.github.io/closure-library/api/[The Google Closure Library API reference]
